### ISSUE TITLE
Exceptions seen with Leiningen 2.8.1 

### ISSUE THREAD

**Issue by codeasone** [walmartlabs/vizdeps#11]
I'm seeing the following exception when running `lein vizdeps` under `Leiningen 2.8.1`: 

```
➜  app lein vizdeps
java.lang.ClassCastException: java.lang.String cannot be cast to clojure.lang.IFn
 at cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic (aether.clj:786)
``` 

Environment details and steps taken to reproduce/isolate: https://gist.github.com/codeasone/5efbc080918c1d63da267e1c618c5b42

Reverting to `Leiningen 2.7.1` restores functionality.

**Comment by viesti** [comment]
A friendly nudge, I'd like a fix too. I got interested on this project after listening the latest The REPL podcast :) https://www.therepl.net/episodes/10/

**Comment by smessems** [comment]
+1

**Comment by AndreaCrotti** [comment]
👍  I can also reproduce it

**Comment by AndreaCrotti** [comment]
Why was this closed @codeasone ?
It doesn't look like it was fixed in the meanwhile right?

**Comment by codeasone** [comment]
Apologies, but it is fixed in the clj-commons fork so I wrongly assumed it
was not longer relevant.

**Comment by AndreaCrotti** [comment]
Ah right, sure, I didn't know there was a clj-commons fork, but it doesn't seem to publish anything on clojars.
If this is the official fork maybe at least this project should mention it:
https://github.com/clj-commons/vizdeps
