### ISSUE TITLE
Potential fork to clj-commons

### ISSUE THREAD

**Issue by cnuernber** [walmartlabs/vizdeps#13]
@hlship 

I have personally found many issues that were almost impossible to debug by visualizing dependencies and as such have an interested professionally on this particular project continuing to be upgraded.

I have personally found many issues that were almost impossible to debug by visualizing dependencies and as such have an interested professionally on this particular project continuing to be upgraded.

There is some [discussion](https://github.com/clj-commons/wishlist/issues/11) about forking this to clj-commons and bringing it up to date to, for instance, work with latest leiningen and jvm releases.

Would you (or any of the contributors to this project) find it distasteful in any way if this project were adopted by clj-commons?

**Comment by hlship** [comment]
I'm all for this, but clj-commons seems to have settled down since we discussed this back in December.

**Comment by cnuernber** [comment]
Agreed.  Closing this to save time, sorry for confusion!
