### ISSUE TITLE
Arity exception resolving dependency inside add-dependency-tree

### ISSUE THREAD

**Issue by xingzheone** [walmartlabs/vizdeps#3]
D:\clojure\luminusweb\yunhaoutil>lein vizdeps -o  target/dependencies.pdf
clojure.lang.ExceptionInfo: Exception processing dependencies of [org.clojure/clojure "1.8.0"]: Exception resolving dep
 at clojure.core$ex_info.invokeStatic (core.clj:4617)
    clojure.core$ex_info.invoke (core.clj:4617)
    leiningen.vizdeps$add_dependency_tree.invokeStatic (vizdeps.clj:106)
    leiningen.vizdeps$add_dependency_tree.invoke (vizdeps.clj:81)
    leiningen.vizdeps$add_dependencies$fn__804.invoke (vizdeps.clj:115)
    clojure.core.protocols$fn__6755.invokeStatic (protocols.clj:167)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$reduce.invoke (core.clj:6527)
    leiningen.vizdeps$add_dependencies.invokeStatic (vizdeps.clj:114)
    leiningen.vizdeps$add_dependencies.invoke (vizdeps.clj:112)
    leiningen.vizdeps$dependency_graph.invokeStatic (vizdeps.clj:146)
    leiningen.vizdeps$dependency_graph.invoke (vizdeps.clj:132)
    leiningen.vizdeps$build_dot.invokeStatic (vizdeps.clj:170)
    leiningen.vizdeps$build_dot.invoke (vizdeps.clj:168)
    leiningen.vizdeps$vizdeps.invokeStatic (vizdeps.clj:225)
    leiningen.vizdeps$vizdeps.doInvoke (vizdeps.clj:206)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5829.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5895.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: clojure.lang.ExceptionInfo: Exception resolving dependencies of [org.clojure/clojure "1.8.0"]: Wrong number
 at clojure.core$ex_info.invokeStatic (core.clj:4617)
    clojure.core$ex_info.invoke (core.clj:4617)
    leiningen.vizdeps$immediate_dependencies.invokeStatic (vizdeps.clj:71)
    leiningen.vizdeps$immediate_dependencies.invoke (vizdeps.clj:56)
    leiningen.vizdeps$add_dependency_tree.invokeStatic (vizdeps.clj:104)
    leiningen.vizdeps$add_dependency_tree.invoke (vizdeps.clj:81)
    leiningen.vizdeps$add_dependencies$fn__804.invoke (vizdeps.clj:115)
    clojure.core.protocols$fn__6755.invokeStatic (protocols.clj:167)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$reduce.invoke (core.clj:6527)
    leiningen.vizdeps$add_dependencies.invokeStatic (vizdeps.clj:114)
    leiningen.vizdeps$add_dependencies.invoke (vizdeps.clj:112)
    leiningen.vizdeps$dependency_graph.invokeStatic (vizdeps.clj:146)
    leiningen.vizdeps$dependency_graph.invoke (vizdeps.clj:132)
    leiningen.vizdeps$build_dot.invokeStatic (vizdeps.clj:170)
    leiningen.vizdeps$build_dot.invoke (vizdeps.clj:168)
    leiningen.vizdeps$vizdeps.invokeStatic (vizdeps.clj:225)
    leiningen.vizdeps$vizdeps.doInvoke (vizdeps.clj:206)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5829.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5895.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: clojure.lang.ArityException: Wrong number of args (4) passed to: classpath/fn--6613
 at clojure.lang.AFn.throwArity (AFn.java:429)
    clojure.lang.AFn.invoke (AFn.java:44)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$memoize$fn__5708.doInvoke (core.clj:6107)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    clojure.lang.Var.invoke (Var.java:394)
    leiningen.vizdeps$immediate_dependencies.invokeStatic (vizdeps.clj:60)
    leiningen.vizdeps$immediate_dependencies.invoke (vizdeps.clj:56)
    leiningen.vizdeps$add_dependency_tree.invokeStatic (vizdeps.clj:104)
    leiningen.vizdeps$add_dependency_tree.invoke (vizdeps.clj:81)
    leiningen.vizdeps$add_dependencies$fn__804.invoke (vizdeps.clj:115)
    clojure.core.protocols$fn__6755.invokeStatic (protocols.clj:167)
    clojure.core.protocols/fn (protocols.clj:124)
    clojure.core.protocols$fn__6710$G__6705__6719.invoke (protocols.clj:19)
    clojure.core.protocols$seq_reduce.invokeStatic (protocols.clj:31)
    clojure.core.protocols$fn__6738.invokeStatic (protocols.clj:75)
    clojure.core.protocols/fn (protocols.clj:75)
    clojure.core.protocols$fn__6684$G__6679__6697.invoke (protocols.clj:13)
    clojure.core$reduce.invokeStatic (core.clj:6545)
    clojure.core$reduce.invoke (core.clj:6527)
    leiningen.vizdeps$add_dependencies.invokeStatic (vizdeps.clj:114)
    leiningen.vizdeps$add_dependencies.invoke (vizdeps.clj:112)
    leiningen.vizdeps$dependency_graph.invokeStatic (vizdeps.clj:146)
    leiningen.vizdeps$dependency_graph.invoke (vizdeps.clj:132)
    leiningen.vizdeps$build_dot.invokeStatic (vizdeps.clj:170)
    leiningen.vizdeps$build_dot.invoke (vizdeps.clj:168)
    leiningen.vizdeps$vizdeps.invokeStatic (vizdeps.clj:225)
    leiningen.vizdeps$vizdeps.doInvoke (vizdeps.clj:206)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5829.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5895.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:436)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)

**Comment by hlship** [comment]
I don't see this, please try to reproduce using 0.1.3, just released.

**Comment by woggle23** [comment]
I also receive the above error, using version `0.1.3`. I've disabled all other plugins. I'm running on Mac OS X El Capitan, Java version `1.8.0_92`,Leiningen `2.6.1` and `2.7.1` (both produce the same output).

**Comment by hlship** [comment]
Ok, a sample project.clj would be a great help.  Even a pointer to a GitHub project.

**Comment by hlship** [comment]
Sorry for the long delay ... hey, what's three years?  Anyway, I don't think this is a problem with more recent versions of vizdeps.
